Feature: Add videos to the database
    In order to readily search and download videos
    As a user
    I would like to be able to tell the videos that I want tracked

    @slow_process
    Scenario: Single video by URL without piping support
        Given I have initialized Ydl on this system
        When  I add a video named "phir se"
        Then  the output should contain "Adding 1 video"
        And   the output should contain "Added 1 video"
        And   the output should contain "Completed: |="
        And   a cache file with metadata for the video should exist
        And   the database file for fuzzy matching of videos should exist
        And   a record for the video should exist in the database
        # When  I run `ydl search phir se`
        # Then  the output should contain 
        # And   searching for "phir se" should show the current video

    Scenario: Adding already added videos
        Given I have initialized Ydl on this system
        When  I add a video named "phir se"
        Then  the output should contain "Added 1 video"
        And   a record for the video should exist in the database
        When  I add a video named "phir se"
        Then  the output should contain "Adding 1 video"
        And   the output should contain "Found 1 existing video"
        And   the output should contain "Added 0 video"

    Scenario: With piping support
        Given I have initialized Ydl on this system
        And   I want to pipe the output of next command
        When  I add a video named "phir se"
        Then  the output should contain the url for the above video
        And   a record for the video should exist in the database

    # NOTE: implies --piped
    Scenario: Without suppressing output from youtube-dl
        Given I have initialized Ydl on this system
        And   I want to see the output generated by youtube-dl
        When  I add a video named "phir se"
        Then  the output should contain the url for the above video
        And   a record for the video should exist in the database

    Scenario: Video with an error
        Given I have initialized Ydl on this system
        And   I want to see the output generated by youtube-dl
        When  I add a video with url "http://?"
        Then  the output should contain the url for the above video
        And   the output should contain "Discarded 1 video"
        And   the output should contain "ERROR: <urlopen error no host given>"
        And   a cache file with metadata for the video should not exist
        And   a record for the video should not exist in the database
