Feature: Downloading videos

	Background:
		Given I have initialized Ydl on this system

	@downloads
	Scenario: Download a video
		When  I download video named "timer"
		Then  the output should contain "Adding 1 video"
		And   the output should contain "Downloading 1 video"
		And   the output should contain "countdown"
		And   the output should contain "Downloaded 1 video"
		And   a record for the video should exist in the database
		And   the downloaded video file should exist
		And   the video should be marked as downloaded in the database
		# NOTE: I wish cucumber had an ELSE step where I could describe
		#		what happens when the error occurs while downloading.

	@downloads
	Scenario: Download multiple videos
		When  I download videos named "timer; timer"
		Then  the output should contain "Adding 1 video"
		And   the output should contain "Downloading 1 video"
		And   the output should contain "Downloaded 1 video"

	Scenario: Download a video with invalid data
		Given I want to see the output generated by youtube-dl
		When  I download video with url "http://?"
		Then  the output should contain "Added 0 video"
		And   the output should contain "Nothing to download"
		And   the output should contain "<urlopen error no host given>"

	# FIXME: How to test this?
	# Scenario: Download a video with an error
	# 	When  I download video with url ""
	# 	Then  the output should contain "Added 1 video"
	# 	And   the output should contain "Downloading 1 video"
	# 	And   the output should contain "Downloaded 0 video"
	# 	And   the output should contain "[WARNING]"
	# TODO: video with an error?
